title: Rodoc
description: App for organizing your family trees.
theme: just-the-docs

url: https://rodoc-app.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
